### ISSUE TITLE
An issue when executing the command bash HCGA-Market1501.sh

### ISSUE THREAD

**Issue by Hanzoe** [Vill-Lab/2022-TIP-HCGA#2]
I followed the steps in the readme to reproduce the process. However, I encountered an issue when executing the command bash HCGA-Market1501.sh, as I am unable to initiate training. Could you please help me identify the problem?

![image](https://github.com/Vill-Lab/2022-TIP-HCGA/assets/46673445/06a5b601-67ef-4410-9404-370784fc0ad4)

  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
>>>>
torch.Size([128, 3, 256, 128])
Working... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
Traceback (most recent call last):
  File "/data/lwh22/project/2022-TIP-HCGA-main/tools/train.py", line 129, in <module>
    main()
  File "/data/lwh22/project/2022-TIP-HCGA-main/tools/train.py", line 125, in main
    train(cfg, num_gpus)
  File "/data/lwh22/project/2022-TIP-HCGA-main/tools/train.py", line 72, in train
    do_train(
  File "/data/lwh22/project/2022-TIP-HCGA-main/./engine/trainer.py", line 627, in do_train
    trainer.run(train_loader, max_epochs=epochs)
  File "/data/lwh22/anaconda3/envs/hcga/lib/python3.9/site-packages/ignite/engine/engine.py", line 359, in run
    self._handle_exception(e)
  File "/data/lwh22/anaconda3/envs/hcga/lib/python3.9/site-packages/ignite/engine/engine.py", line 324, in _handle_exception
    raise e
  File "/data/lwh22/anaconda3/envs/hcga/lib/python3.9/site-packages/ignite/engine/engine.py", line 345, in run
    self._fire_event(Events.EPOCH_STARTED)
  File "/data/lwh22/anaconda3/envs/hcga/lib/python3.9/site-packages/ignite/engine/engine.py", line 259, in _fire_event
    func(self, *(event_args + args), **kwargs)
  File "/data/lwh22/project/2022-TIP-HCGA-main/./engine/trainer.py", line 480, in adjust_mask_pseudo_labels
    feats, pseudo_labels_paths, pids, shape = compute_features(clustering_loader, model, device, with_arm)
  File "/data/lwh22/project/2022-TIP-HCGA-main/./engine/trainer.py", line 170, in compute_features
    batch_feats = model(batch_img, compute_futures=True)
  File "/data/lwh22/anaconda3/envs/hcga/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'compute_futures'

**Comment by shuguang-52** [comment]
Does this problem occur in other .sh files?

**Comment by Hanzoe** [comment]
yes, would you happen to know how to fix it? Is this error about the environment or the code?

**Comment by zhaoruochi** [comment]
> yes, would you happen to know how to fix it? Is this error about the environment or the code?

I also encountered this problem, how did you solve it

**Comment by shuguang-52** [comment]
Sorry for the late reply as I've been busy with job hunting and graduation lately. I've updated the trainer.py and hopefully it will work fine after that.
